# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17warehouse_manager.proto\x12\x0cwarehouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"X\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12(\n\x08location\x18\x03 \x01(\x0b\x32\x16.warehouse.v1.GeoPoint\"\xb8\x01\n\rWarehouseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12(\n\x08location\x18\x03 \x01(\x0b\x32\x16.warehouse.v1.GeoPoint\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"$\n\x08GeoPoint\x12\x0b\n\x03lon\x18\x01 \x01(\x01\x12\x0b\n\x03lat\x18\x02 \x01(\x01\"\x1d\n\rDeleteRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\"1\n\x08Response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x06status\x18\x02 \x01(\x0e\x32\x07.Status\"<\n\x0cInfoResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.warehouse.v1.WarehouseInfo2\xf9\x01\n\x17WarehouseManagerService\x12H\n\x0f\x43reateWarehouse\x12\x1b.warehouse.v1.CreateRequest\x1a\x16.warehouse.v1.Response\"\x00\x12H\n\x0f\x44\x65leteWarehouse\x12\x1b.warehouse.v1.DeleteRequest\x1a\x16.warehouse.v1.Response\"\x00\x12J\n\x12\x45xistingWarehouses\x12\x16.google.protobuf.Empty\x1a\x1a.warehouse.v1.InfoResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUEST._serialized_start=117
  _CREATEREQUEST._serialized_end=205
  _WAREHOUSEINFO._serialized_start=208
  _WAREHOUSEINFO._serialized_end=392
  _GEOPOINT._serialized_start=394
  _GEOPOINT._serialized_end=430
  _DELETEREQUEST._serialized_start=432
  _DELETEREQUEST._serialized_end=461
  _RESPONSE._serialized_start=463
  _RESPONSE._serialized_end=512
  _INFORESPONSE._serialized_start=514
  _INFORESPONSE._serialized_end=574
  _WAREHOUSEMANAGERSERVICE._serialized_start=577
  _WAREHOUSEMANAGERSERVICE._serialized_end=826
# @@protoc_insertion_point(module_scope)
